#! /bin/sh

DATE="<strong>$1</strong>"
LINK_START="<a href=\"$2\">"
LINK_END="</a>"
NAME="$3"
ENTRY="\      <li class=\"tournaments-entry\">$LINK_START$DATE &mdash; $NAME$LINK_END</li>"

sed -i -e '/<ul class="tournaments-list">/a '"$ENTRY" _includes/tournaments.html

