# Site settings
title: Interaktywny Kurs Go
description: >
  Interaktywny kurs Go.
url: "https://kursgo.pl" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
port: 8000

# lessons placeholder
pages: ./_lessons

# default layout for lessons
layout: default

plugins:
- jekyll-watch
- jekyll-assets

# jekyll-assets configuration
assets:
  digest: true
# js_compressor:  uglifier
  css_compressor: scss
  sources:
  - _assets/stylesheets
  - _assets/javascripts