# Site settings
title: Interaktywny Kurs Go
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Interaktywny kurs Go.
url: "http://kursgo.pl" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
port: 8000

#collections:
#  lessons:
#    output: true
#    permalink: /lekcja/:path/

defaults:
-
  scope:
    path: ""
  values:
    layout: "default"
